services:
  - type: web
    name: poke-hunter-mmo
    env: python
    buildCommand: "./build.sh" # или ваша команда сборки
    envVars:
      - key: CARGO_HOME
        value: /opt/render/project/src/.cargo
